[package]
name = "nightshift"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
fuser = "0.14.0"
libc = "0.2.155"
log = "0.4.22"
rusqlite = "0.32.1"
signal-hook = "0.3.17"
simple_logger = "5.0.0"

[profile.release]
debug = true
