use std::{
    collections::{BTreeMap, HashMap},
    ffi::{OsStr, OsString},
    sync::Arc,
};

use fuser::FileAttr;
use parking_lot::Mutex;
use slab::Slab;

use crate::{database::DatabaseOps, driver::OpenFlags, queries};

use super::{Fno, Ino, Vfs, VfsHandle};

struct WriteBehindCore {
    //db: DatabaseOps, // todo use connection pool
    pool: r2d2::Pool<r2d2_sqlite::SqliteConnectionManager>,
    nodes: parking_lot::RwLock<BTreeMap<Ino, FileAttr>>,
    entries: parking_lot::RwLock<HashMap<OsString, Ino>>,
    handles: parking_lot::RwLock<Slab<WriteBehindHandle>>,
    read_lock: Mutex<()>, // todo striped lock
}

#[derive(Clone)]
struct WriteBehind {
    core: Arc<WriteBehindCore>,
}

#[derive(Clone)]
struct WriteBehindHandle {
    fno: Fno,
    core: Arc<WriteBehindCore>,
    flags: OpenFlags,
}

impl WriteBehind {}

impl Vfs for WriteBehind {
    type Handle = WriteBehindHandle;
    type Error = crate::errors::Error;

    fn ensure_root(&self) -> Result<(), Self::Error> {
        todo!()
    }

    fn lookup_name(&self, parent: super::Ino, name: &OsStr) -> Result<fuser::FileAttr, Self::Error> {
        let _read_guard = self.core.read_lock.lock();
        let ino = match self.core.entries.read().get(name).copied() {
            Some(ino) => ino,
            None => {
                // Either the entry does not exist or has no been loaded yet, try to load it.
                let mut conn = self.core.pool.get()?;
                let mut tx = conn.transaction()?;
                let ino = queries::dir_entry::lookup(&mut tx, parent.0, name)?;
                self.core.entries.write().insert(name.to_owned(), ino.into());
                ino.into()
            }
        };
        self.lookup_ino(ino)
    }

    fn lookup_ino(&self, ino: super::Ino) -> Result<fuser::FileAttr, Self::Error> {
        let _read_guard = self.core.read_lock.lock();
        match self.core.nodes.read().get(&ino).copied() {
            Some(attr) => Ok(attr),
            None => {
                // Either the node does not exist or has no been loaded yet, try to load it.
                let mut conn = self.core.pool.get()?;
                let mut tx = conn.transaction()?;
                let inode = queries::inode::lookup(&mut tx, ino.0)?;
                self.core.nodes.write().insert(ino, inode);
                Ok(inode)
            }
        }
    }

    fn open(&self, ino: super::Ino, flags: OpenFlags) -> Result<Self::Handle, Self::Error> {
        self.lookup_ino(ino)?;
        let handle = WriteBehindHandle {
            fno: 0u64.into(), // generated by slab
            core: self.core.clone(),
            flags,
        };
        let mut handles = self.core.handles.write();
        let fno = handles.insert(handle);
        let handle = &mut handles[fno];
        handle.fno = fno.into();
        Ok(handle.clone())
    }

    fn close(&self, fno: super::Fno) -> Result<(), Self::Error> {
        let h = self.handle(fno).ok_or_else(|| crate::errors::Error::NotFound)?;
        h.flush()?;
        self.core.handles.write().remove(fno.into());
        Ok(())
    }

    fn handle(&self, fno: super::Fno) -> Option<Self::Handle> {
        self.core.handles.read().get(fno.into()).cloned()
    }
}

impl VfsHandle for WriteBehindHandle {
    type Error = crate::errors::Error;

    fn fno(&self) -> Fno {
        self.fno
    }

    fn read(&self, offset: u64, size: u32) -> Result<bytes::Bytes, Self::Error> {
        todo!()
    }

    fn write(&self, offset: u64, data: &[u8]) -> Result<(), Self::Error> {
        todo!()
    }

    fn flush(&self) -> Result<(), Self::Error> {
        todo!()
    }
}
